name: update-dotnet-sdk

on:
  schedule:
    - cron:  '00 19 * * TUE'
  workflow_dispatch:

permissions: {}

jobs:
  update-sdk:
    uses: martincostello/update-dotnet-sdk/.github/workflows/update-dotnet-sdk.yml@a56c6d7f553ce7cacfaae732159694894268742c # v3.8.3
    with:
      labels: "dependencies,.NET"
      update-nuget-packages: false
      user-email: ${{ vars.UPDATER_COMMIT_USER_EMAIL }}
      user-name: ${{ vars.UPDATER_COMMIT_USER_NAME }}
    secrets:
      application-id: ${{ secrets.UPDATER_APPLICATION_ID }}
      application-private-key: ${{ secrets.UPDATER_APPLICATION_PRIVATE_KEY }}
