name: update-dotnet-sdk

on:
  schedule:
    - cron:  '00 19 * * TUE'
  workflow_dispatch:

permissions: {}

jobs:
  update-sdk:
    uses: martincostello/update-dotnet-sdk/.github/workflows/update-dotnet-sdk.yml@ef7653ed976c929ef8c6c6bd31c45b4675c2de71 # v3.6.0
    with:
      labels: "dependencies,.NET"
      update-nuget-packages: false
      user-email: ${{ vars.UPDATER_COMMIT_USER_EMAIL }}
      user-name: ${{ vars.UPDATER_COMMIT_USER_NAME }}
    secrets:
      application-id: ${{ secrets.UPDATER_APPLICATION_ID }}
      application-private-key: ${{ secrets.UPDATER_APPLICATION_PRIVATE_KEY }}
